/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ee5bb76d-420b-44a6-8b64-b966c2abfa15",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CWWb4wHdm",
    "aws_user_pools_web_client_id": "24236ogpa4kr10isutvqlglekh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://irnzr4sa6be5rm5eb6txvn7qey.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_user_files_s3_bucket": "rap-clouds-cloud-bucket154829-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
